"""add backtest_observations table

Revision ID: 3d430b826177
Revises: 59e7ad99b7da
Create Date: 2026-05-22 19:03:01.866276

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d430b826177'
down_revision: Union[str, None] = '59e7ad99b7da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backtest_observations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('fy_end', sa.Date(), nullable=False),
    sa.Column('as_of', sa.Date(), nullable=False),
    sa.Column('sector', sa.String(), nullable=True),
    sa.Column('horizon_months', sa.Integer(), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('risk_label', sa.String(), nullable=True),
    sa.Column('valuation_label', sa.String(), nullable=True),
    sa.Column('upside_pct', sa.Float(), nullable=True),
    sa.Column('base_target', sa.Float(), nullable=True),
    sa.Column('price_at_as_of', sa.Float(), nullable=True),
    sa.Column('forward_return_pct', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('backtest_observations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_backtest_observations_as_of'), ['as_of'], unique=False)
        batch_op.create_index(batch_op.f('ix_backtest_observations_ticker'), ['ticker'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('backtest_observations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_backtest_observations_ticker'))
        batch_op.drop_index(batch_op.f('ix_backtest_observations_as_of'))

    op.drop_table('backtest_observations')
    # ### end Alembic commands ###
