"""add sector_profiles table

Revision ID: 5811028fa0db
Revises: b46328ae6827
Create Date: 2026-05-22 19:19:28.784234

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5811028fa0db'
down_revision: Union[str, None] = 'b46328ae6827'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sector_profiles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sector', sa.String(), nullable=False),
    sa.Column('metric', sa.String(), nullable=False),
    sa.Column('median', sa.Float(), nullable=False),
    sa.Column('spread', sa.Float(), nullable=False),
    sa.Column('sample_size', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sector', 'metric', name='uq_sector_profile')
    )
    with op.batch_alter_table('sector_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sector_profiles_sector'), ['sector'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sector_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sector_profiles_sector'))

    op.drop_table('sector_profiles')
    # ### end Alembic commands ###
