"""add BCSI and quality columns to companies

Revision ID: 5be4d2830bd1
Revises: eab47a1a1fbb
Create Date: 2026-05-24 13:09:47.616975

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5be4d2830bd1'
down_revision: Union[str, None] = 'eab47a1a1fbb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quality_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('quality_label', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('piotroski_f_score', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('graham_number', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('bcsi_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('bcsi_label', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('bcsi_dimensions', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('bcsi_confidence', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_column('bcsi_confidence')
        batch_op.drop_column('bcsi_dimensions')
        batch_op.drop_column('bcsi_label')
        batch_op.drop_column('bcsi_score')
        batch_op.drop_column('graham_number')
        batch_op.drop_column('piotroski_f_score')
        batch_op.drop_column('quality_label')
        batch_op.drop_column('quality_score')

    # ### end Alembic commands ###
