"""initial schema

Revision ID: ac026212f36e
Revises: 
Create Date: 2026-05-22 11:17:39.114058

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac026212f36e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('sector', sa.String(), nullable=True),
    sa.Column('sub_sector', sa.String(), nullable=True),
    sa.Column('market_cap', sa.Float(), nullable=True),
    sa.Column('current_price', sa.Float(), nullable=True),
    sa.Column('fifty_two_week_high', sa.Float(), nullable=True),
    sa.Column('fifty_two_week_low', sa.Float(), nullable=True),
    sa.Column('beta', sa.Float(), nullable=True),
    sa.Column('revenue_ttm', sa.Float(), nullable=True),
    sa.Column('revenue_growth_yoy', sa.Float(), nullable=True),
    sa.Column('earnings_growth', sa.Float(), nullable=True),
    sa.Column('net_margin', sa.Float(), nullable=True),
    sa.Column('roa', sa.Float(), nullable=True),
    sa.Column('roe', sa.Float(), nullable=True),
    sa.Column('pe_ratio', sa.Float(), nullable=True),
    sa.Column('forward_pe', sa.Float(), nullable=True),
    sa.Column('peg_ratio', sa.Float(), nullable=True),
    sa.Column('ev_ebitda', sa.Float(), nullable=True),
    sa.Column('ev_revenue', sa.Float(), nullable=True),
    sa.Column('eps_ttm', sa.Float(), nullable=True),
    sa.Column('eps_forward', sa.Float(), nullable=True),
    sa.Column('debt_to_equity', sa.Float(), nullable=True),
    sa.Column('current_ratio', sa.Float(), nullable=True),
    sa.Column('total_cash', sa.Float(), nullable=True),
    sa.Column('total_debt', sa.Float(), nullable=True),
    sa.Column('shares_outstanding', sa.Float(), nullable=True),
    sa.Column('free_cashflow', sa.Float(), nullable=True),
    sa.Column('analyst_target_mean', sa.Float(), nullable=True),
    sa.Column('analyst_target_high', sa.Float(), nullable=True),
    sa.Column('analyst_target_low', sa.Float(), nullable=True),
    sa.Column('analyst_count', sa.Integer(), nullable=True),
    sa.Column('recommendation', sa.String(), nullable=True),
    sa.Column('dividend_yield', sa.Float(), nullable=True),
    sa.Column('payout_ratio', sa.Float(), nullable=True),
    sa.Column('altman_z_score', sa.Float(), nullable=True),
    sa.Column('altman_zone', sa.String(), nullable=True),
    sa.Column('beneish_m_score', sa.Float(), nullable=True),
    sa.Column('beneish_flag', sa.String(), nullable=True),
    sa.Column('icr', sa.Float(), nullable=True),
    sa.Column('icr_label', sa.String(), nullable=True),
    sa.Column('fcf_margin', sa.Float(), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('risk_label', sa.String(), nullable=True),
    sa.Column('risk_confidence', sa.Float(), nullable=True),
    sa.Column('risk_flags', sa.Text(), nullable=True),
    sa.Column('risk_components', sa.Text(), nullable=True),
    sa.Column('sector_calibrated', sa.Boolean(), nullable=True),
    sa.Column('dcf_fair_value', sa.Float(), nullable=True),
    sa.Column('pe_fair_value', sa.Float(), nullable=True),
    sa.Column('peg_fair_value', sa.Float(), nullable=True),
    sa.Column('analyst_consensus', sa.Float(), nullable=True),
    sa.Column('composite_fair_value', sa.Float(), nullable=True),
    sa.Column('upside_pct', sa.Float(), nullable=True),
    sa.Column('valuation_label', sa.String(), nullable=True),
    sa.Column('valuation_confidence', sa.Float(), nullable=True),
    sa.Column('bear_target', sa.Float(), nullable=True),
    sa.Column('base_target', sa.Float(), nullable=True),
    sa.Column('bull_target', sa.Float(), nullable=True),
    sa.Column('stretched_bull_target', sa.Float(), nullable=True),
    sa.Column('entry_zone_low', sa.Float(), nullable=True),
    sa.Column('entry_zone_high', sa.Float(), nullable=True),
    sa.Column('trim_level', sa.Float(), nullable=True),
    sa.Column('hard_stop', sa.Float(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('ticker')
    )
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_companies_sector'), ['sector'], unique=False)
        batch_op.create_index(batch_op.f('ix_companies_ticker'), ['ticker'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_companies_ticker'))
        batch_op.drop_index(batch_op.f('ix_companies_sector'))

    op.drop_table('companies')
    # ### end Alembic commands ###
