"""add governance_records table

Revision ID: eab47a1a1fbb
Revises: 5811028fa0db
Create Date: 2026-05-22 23:42:38.850284

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eab47a1a1fbb'
down_revision: Union[str, None] = '5811028fa0db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('governance_records',
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('promoter_holding_pct', sa.Float(), nullable=True),
    sa.Column('promoter_pledge_pct', sa.Float(), nullable=True),
    sa.Column('promoter_pledge_pct_prior', sa.Float(), nullable=True),
    sa.Column('auditor_name', sa.String(), nullable=True),
    sa.Column('auditor_changed_recently', sa.Boolean(), nullable=True),
    sa.Column('sebi_action_pending', sa.Boolean(), nullable=True),
    sa.Column('sebi_action_count', sa.Integer(), nullable=True),
    sa.Column('board_size', sa.Integer(), nullable=True),
    sa.Column('independent_director_count', sa.Integer(), nullable=True),
    sa.Column('governance_score', sa.Float(), nullable=True),
    sa.Column('governance_label', sa.String(), nullable=True),
    sa.Column('governance_flags', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('ticker')
    )
    with op.batch_alter_table('governance_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_governance_records_ticker'), ['ticker'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('governance_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_governance_records_ticker'))

    op.drop_table('governance_records')
    # ### end Alembic commands ###
